export const START_POLLING = "START_POLLING";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const TOGGLE_APPLY_DISCOUNTS = "TOGGLE_APPLY_DISCOUNTS";
export const TOGGLE_MARK_DUPLICATES = "TOGGLE_MARK_DUPLICATES";
export const TOGGLE_SHOW_UNDOCUMENTED = "TOGGLE_SHOW_UNDOCUMENTED";
